### PR TITLE
Firefox

### PR DESCRIPTION
**Pull request by talklittle**
Got it working on Firefox by:

1. Skipping incompatible Chrome APIs
2. Updating video.js and videojs-contrib-hls to latest stable versions

Tested on Firefox 50.0a2 (Developer Edition), on Ubuntu 16.04 and OSX 10.11.6. Flash plugin blocked.

### CODE REVIEW

**Comment by KolbyClark** [comment]
I have updated the extension a few times since the last time I pushed to here, but I have now made the changes in this pull and am working on publishing in the add-on site right now. Thanks for the heads up.

**Comment by talklittle** [comment]
@KolbyClark Great! Thank you!

**Comment by KolbyClark** [comment]
I am glad to see that it is finally working on Firefox. I have tried it every couple of months since I heard about webextensions.

**Comment by talklittle** [comment]
Just note that it doesn't seem to work on Firefox 48, and I haven't tested 49. So it may be a few months before users get Firefox 50 and can use your extension. Release date is early November.

**Comment by adamthiede** [comment]
How did you get this working on Firefox? Do you need an HLS extension or does this provide that?
I'm getting errors in debugging that look like this:
MEDIA_ERR_SRC_NOT_SUPPORTED
Cannot play media. No decoders for requested formats: application/x-mpegURL, application/x-mpegURL
Same thing on Linux and macOS.
Sorry if this is the wrong place to put this. I know it's been a year since.

**Comment by talklittle** [comment]
@adamthiede If I remember correctly, those errors were fixed by updating to Firefox 50, and updating the video.js and video-contrib-hls libraries. It's possible something broke since then. I haven't actually used this extension in a while.

**Pull request closed without merging**
